grammar at.ac.tuwien.big.Scml with org.eclipse.xtext.common.Terminals

import "http://www.example.org/scml" 
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

SmartCity returns SmartCity:
	{SmartCity}
	'SmartCity'
	name=EString
	'{'
		
	'}';


EFloat returns ecore::EFloat:
	'-'? INT? '.' INT (('E'|'e') '-'? INT)?;


EBoolean returns ecore::EBoolean:
	'true' | 'false';

EString returns ecore::EString:
	STRING | ID;
	
EInt returns ecore::EInt:
	'-'? INT;