/*
 * generated by Xtext 2.31.0
 */
package at.ac.tuwien.big.ide.contentassist.antlr;

import at.ac.tuwien.big.ide.contentassist.antlr.internal.InternalScmlParser;
import at.ac.tuwien.big.services.ScmlGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ScmlParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ScmlGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ScmlGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInfrastructureComponentAccess().getAlternatives(), "rule__InfrastructureComponent__Alternatives");
			builder.put(grammarAccess.getDeviceAccess().getAlternatives(), "rule__Device__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
			builder.put(grammarAccess.getPrincipleTypeAccess().getAlternatives(), "rule__PrincipleType__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getStatusAccess().getAlternatives(), "rule__Status__Alternatives");
			builder.put(grammarAccess.getSmartCityAccess().getGroup(), "rule__SmartCity__Group__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_4(), "rule__SmartCity__Group_4__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_4_3(), "rule__SmartCity__Group_4_3__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_5(), "rule__SmartCity__Group_5__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_5_3(), "rule__SmartCity__Group_5_3__0");
			builder.put(grammarAccess.getCategoryAccess().getGroup(), "rule__Category__Group__0");
			builder.put(grammarAccess.getCategoryAccess().getGroup_6(), "rule__Category__Group_6__0");
			builder.put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_4(), "rule__Project__Group_4__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_4_3(), "rule__Project__Group_4_3__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_5(), "rule__Project__Group_5__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_5_3(), "rule__Project__Group_5_3__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_6(), "rule__Project__Group_6__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_6_3(), "rule__Project__Group_6_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup(), "rule__KPIMeasurementDevice__Group__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_5(), "rule__KPIMeasurementDevice__Group_5__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_5_3(), "rule__KPIMeasurementDevice__Group_5_3__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_8(), "rule__KPIMeasurementDevice__Group_8__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getDataValueAccess().getGroup(), "rule__DataValue__Group__0");
			builder.put(grammarAccess.getDataValueAccess().getGroup_9(), "rule__DataValue__Group_9__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_11(), "rule__Parameter__Group_11__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup(), "rule__BuildingComponent__Group__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_3(), "rule__BuildingComponent__Group_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_4(), "rule__BuildingComponent__Group_4__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_4_3(), "rule__BuildingComponent__Group_4_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_7(), "rule__BuildingComponent__Group_7__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_7_3(), "rule__BuildingComponent__Group_7_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_10(), "rule__BuildingComponent__Group_10__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_10_3(), "rule__BuildingComponent__Group_10_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup(), "rule__TransportationComponent__Group__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_3(), "rule__TransportationComponent__Group_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_4(), "rule__TransportationComponent__Group_4__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_4_3(), "rule__TransportationComponent__Group_4_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_7(), "rule__TransportationComponent__Group_7__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_7_3(), "rule__TransportationComponent__Group_7_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_10(), "rule__TransportationComponent__Group_10__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_10_3(), "rule__TransportationComponent__Group_10_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup(), "rule__EnvironmentalComponent__Group__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_3(), "rule__EnvironmentalComponent__Group_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_4(), "rule__EnvironmentalComponent__Group_4__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_4_3(), "rule__EnvironmentalComponent__Group_4_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_7(), "rule__EnvironmentalComponent__Group_7__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_7_3(), "rule__EnvironmentalComponent__Group_7_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_10(), "rule__EnvironmentalComponent__Group_10__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_10_3(), "rule__EnvironmentalComponent__Group_10_3__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getGroup(), "rule__GoalReferenceValue__Group__0");
			builder.put(grammarAccess.getAggregatedValueAccess().getGroup(), "rule__AggregatedValue__Group__0");
			builder.put(grammarAccess.getBasisAccess().getGroup(), "rule__Basis__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getSmartCityAccess().getNameAssignment_2(), "rule__SmartCity__NameAssignment_2");
			builder.put(grammarAccess.getSmartCityAccess().getCategoryAssignment_4_2(), "rule__SmartCity__CategoryAssignment_4_2");
			builder.put(grammarAccess.getSmartCityAccess().getCategoryAssignment_4_3_1(), "rule__SmartCity__CategoryAssignment_4_3_1");
			builder.put(grammarAccess.getSmartCityAccess().getProjectAssignment_5_2(), "rule__SmartCity__ProjectAssignment_5_2");
			builder.put(grammarAccess.getSmartCityAccess().getProjectAssignment_5_3_1(), "rule__SmartCity__ProjectAssignment_5_3_1");
			builder.put(grammarAccess.getCategoryAccess().getNameAssignment_1(), "rule__Category__NameAssignment_1");
			builder.put(grammarAccess.getCategoryAccess().getSDGAssignment_5(), "rule__Category__SDGAssignment_5");
			builder.put(grammarAccess.getCategoryAccess().getSDGAssignment_6_1(), "rule__Category__SDGAssignment_6_1");
			builder.put(grammarAccess.getProjectAccess().getNameAssignment_2(), "rule__Project__NameAssignment_2");
			builder.put(grammarAccess.getProjectAccess().getCategoryAssignment_4_2(), "rule__Project__CategoryAssignment_4_2");
			builder.put(grammarAccess.getProjectAccess().getCategoryAssignment_4_3_1(), "rule__Project__CategoryAssignment_4_3_1");
			builder.put(grammarAccess.getProjectAccess().getComponentAssignment_5_2(), "rule__Project__ComponentAssignment_5_2");
			builder.put(grammarAccess.getProjectAccess().getComponentAssignment_5_3_1(), "rule__Project__ComponentAssignment_5_3_1");
			builder.put(grammarAccess.getProjectAccess().getIndicatorAssignment_6_2(), "rule__Project__IndicatorAssignment_6_2");
			builder.put(grammarAccess.getProjectAccess().getIndicatorAssignment_6_3_1(), "rule__Project__IndicatorAssignment_6_3_1");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getNameAssignment_1(), "rule__KPIMeasurementDevice__NameAssignment_1");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getStatusAssignment_4(), "rule__KPIMeasurementDevice__StatusAssignment_4");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getLastCalculationAssignment_5_2(), "rule__KPIMeasurementDevice__LastCalculationAssignment_5_2");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getLastCalculationAssignment_5_3_1(), "rule__KPIMeasurementDevice__LastCalculationAssignment_5_3_1");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getNextCalculationAssignment_7(), "rule__KPIMeasurementDevice__NextCalculationAssignment_7");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getParameterAssignment_8_1(), "rule__KPIMeasurementDevice__ParameterAssignment_8_1");
			builder.put(grammarAccess.getLocationAccess().getLatAssignment_3(), "rule__Location__LatAssignment_3");
			builder.put(grammarAccess.getLocationAccess().getLongAssignment_5(), "rule__Location__LongAssignment_5");
			builder.put(grammarAccess.getDataValueAccess().getCollectedAssignment_0(), "rule__DataValue__CollectedAssignment_0");
			builder.put(grammarAccess.getDataValueAccess().getTypeAssignment_4(), "rule__DataValue__TypeAssignment_4");
			builder.put(grammarAccess.getDataValueAccess().getValueAssignment_6(), "rule__DataValue__ValueAssignment_6");
			builder.put(grammarAccess.getDataValueAccess().getProducedTimeAssignment_8(), "rule__DataValue__ProducedTimeAssignment_8");
			builder.put(grammarAccess.getDataValueAccess().getConsumedTimeAssignment_9_1(), "rule__DataValue__ConsumedTimeAssignment_9_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
			builder.put(grammarAccess.getParameterAccess().getUnitAssignment_4(), "rule__Parameter__UnitAssignment_4");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_6(), "rule__Parameter__TypeAssignment_6");
			builder.put(grammarAccess.getParameterAccess().getComponentAssignment_8(), "rule__Parameter__ComponentAssignment_8");
			builder.put(grammarAccess.getParameterAccess().getGoalreferencevalueAssignment_10(), "rule__Parameter__GoalreferencevalueAssignment_10");
			builder.put(grammarAccess.getParameterAccess().getObservedValueAssignment_11_1(), "rule__Parameter__ObservedValueAssignment_11_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getNameAssignment_1(), "rule__BuildingComponent__NameAssignment_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getIsPartOfAssignment_3_1(), "rule__BuildingComponent__IsPartOfAssignment_3_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getComposedOfAssignment_4_2(), "rule__BuildingComponent__ComposedOfAssignment_4_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getComposedOfAssignment_4_3_1(), "rule__BuildingComponent__ComposedOfAssignment_4_3_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getLocationAssignment_6(), "rule__BuildingComponent__LocationAssignment_6");
			builder.put(grammarAccess.getBuildingComponentAccess().getProducesAssignment_7_2(), "rule__BuildingComponent__ProducesAssignment_7_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getProducesAssignment_7_3_1(), "rule__BuildingComponent__ProducesAssignment_7_3_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getParameterAssignment_9(), "rule__BuildingComponent__ParameterAssignment_9");
			builder.put(grammarAccess.getBuildingComponentAccess().getDeviceAssignment_10_2(), "rule__BuildingComponent__DeviceAssignment_10_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getDeviceAssignment_10_3_1(), "rule__BuildingComponent__DeviceAssignment_10_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getNameAssignment_1(), "rule__TransportationComponent__NameAssignment_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getIsPartOfAssignment_3_1(), "rule__TransportationComponent__IsPartOfAssignment_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getComposedOfAssignment_4_2(), "rule__TransportationComponent__ComposedOfAssignment_4_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getComposedOfAssignment_4_3_1(), "rule__TransportationComponent__ComposedOfAssignment_4_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getLocationAssignment_6(), "rule__TransportationComponent__LocationAssignment_6");
			builder.put(grammarAccess.getTransportationComponentAccess().getProducesAssignment_7_2(), "rule__TransportationComponent__ProducesAssignment_7_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getProducesAssignment_7_3_1(), "rule__TransportationComponent__ProducesAssignment_7_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getParameterAssignment_9(), "rule__TransportationComponent__ParameterAssignment_9");
			builder.put(grammarAccess.getTransportationComponentAccess().getDeviceAssignment_10_2(), "rule__TransportationComponent__DeviceAssignment_10_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getDeviceAssignment_10_3_1(), "rule__TransportationComponent__DeviceAssignment_10_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getNameAssignment_1(), "rule__EnvironmentalComponent__NameAssignment_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getIsPartOfAssignment_3_1(), "rule__EnvironmentalComponent__IsPartOfAssignment_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getComposedOfAssignment_4_2(), "rule__EnvironmentalComponent__ComposedOfAssignment_4_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getComposedOfAssignment_4_3_1(), "rule__EnvironmentalComponent__ComposedOfAssignment_4_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getLocationAssignment_6(), "rule__EnvironmentalComponent__LocationAssignment_6");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getProducesAssignment_7_2(), "rule__EnvironmentalComponent__ProducesAssignment_7_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getProducesAssignment_7_3_1(), "rule__EnvironmentalComponent__ProducesAssignment_7_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getParameterAssignment_9(), "rule__EnvironmentalComponent__ParameterAssignment_9");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getDeviceAssignment_10_2(), "rule__EnvironmentalComponent__DeviceAssignment_10_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getDeviceAssignment_10_3_1(), "rule__EnvironmentalComponent__DeviceAssignment_10_3_1");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getTypeAssignment_3(), "rule__GoalReferenceValue__TypeAssignment_3");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getValueAssignment_5(), "rule__GoalReferenceValue__ValueAssignment_5");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getBasisAssignment_7(), "rule__GoalReferenceValue__BasisAssignment_7");
			builder.put(grammarAccess.getAggregatedValueAccess().getTypeAssignment_3(), "rule__AggregatedValue__TypeAssignment_3");
			builder.put(grammarAccess.getAggregatedValueAccess().getValueAssignment_5(), "rule__AggregatedValue__ValueAssignment_5");
			builder.put(grammarAccess.getAggregatedValueAccess().getAggregatorAssignment_7(), "rule__AggregatedValue__AggregatorAssignment_7");
			builder.put(grammarAccess.getAggregatedValueAccess().getAggregatedTimeAssignment_9(), "rule__AggregatedValue__AggregatedTimeAssignment_9");
			builder.put(grammarAccess.getBasisAccess().getDescriptionAssignment_3(), "rule__Basis__DescriptionAssignment_3");
			builder.put(grammarAccess.getBasisAccess().getPrincipleTypeAssignment_5(), "rule__Basis__PrincipleTypeAssignment_5");
			builder.put(grammarAccess.getBasisAccess().getSourceAssignment_7(), "rule__Basis__SourceAssignment_7");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_1(), "rule__Sensor__NameAssignment_1");
			builder.put(grammarAccess.getSensorAccess().getTypeAssignment_4(), "rule__Sensor__TypeAssignment_4");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_1(), "rule__Actuator__NameAssignment_1");
			builder.put(grammarAccess.getActuatorAccess().getTypeAssignment_4(), "rule__Actuator__TypeAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ScmlGrammarAccess grammarAccess;

	@Override
	protected InternalScmlParser createParser() {
		InternalScmlParser result = new InternalScmlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ScmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
